### ISSUE TITLE
Container creates it's own volumes for the filesystem backend and the logging backend.

### ISSUE THREAD

**Issue by memotype** [hashicorp/docker-vault#58]
From the Docker host, I am mapping (with -v) /var/lib/vault to /vault on the container. Under this directory I have config, file and log directories. In the HCL under the config directory, I am configuring the filesystem backend with:

```
storage "file" {
  path = "/vault/file"
}
```

But the files Vault writes there in the container don't show up on the host.

```
bash-4.2# docker exec vault ls -l /vault/file
total 0
drwxr-xr-x    4 vault    vault          190 Oct 16 21:02 core
drwxr-xr-x    4 vault    vault           33 Oct 16 21:02 sys
bash-4.2# ls -l /var/lib/vault/file
total 0
bash-4.2#
```

When I look at `docker inspect` I see that the container is over-riding the mount with it's own volume:

```
        "Mounts": [
            {
                "Source": "/var/lib/vault",
                "Destination": "/vault",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Name": "501e025f5b60bb2507cbbc2d68798e6c88f5c4e7fa8dfc17b1235cef092ba07c",
                "Source": "/var/lib/docker/volumes/501e025f5b60bb2507cbbc2d68798e6c88f5c4e7fa8dfc17b1235cef092ba07c/_data",
                "Destination": "/vault/file",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
```

How am I supposed to persist the Vault data if it's creating it's own volume every time?

**Comment by jefferai** [comment]
If you look at https://github.com/hashicorp/docker-vault/blob/master/0.X/Dockerfile you can see that it's declaring two volumes: /vault/file and /vault/logs. They're declared as volumes specifically *to* allow for persisted data.

If you want to override them, you may need to override the actual paths instead of a higher level path. You'll need to consult Docker documentation for more info on overriding these statements, but what's there is the method that was recommended to us by the Docker team during review of our Dockerfile. Since we're basing it on best practices communicated to us directly from the Docker team, we don't plan on changing it.

**Comment by memotype** [comment]
Ok, so I admit I'm a bit new to Docker. I've spent all morning Googling and reading docs, so while I know this is likely a "Docker thing" and not a "Vault thing", I'm just curious if you could give me some tips on how to  manage this.

So, the systemd service file I have on my Atomic host does a "docker run ..." and creates a new container to start the "docker-vault" service, and a "docker stop ..." followed by a "docker rm ...". So, whenever I restart the docker-vault service, a new container is created with new volumes. I did check "docker volume ls" and I do see a bunch of randomly named volumes, so the old data is being persisted, but it's not being reused when the container is recreated.

So, my question is, how would you recommend starting and stopping the container in a way that reuses the same volume instead of creating a new one each time?

**Comment by jefferai** [comment]
I know nothing about Atomic, very little about systemd, and a decent amount about Docker operationally but very little about volumes since I never use them. The only suggestion I can give is what I gave before, which is, bind mount to the volumes defined in the file (/vault/logs and /vault/file) rather than to the top level and see if that works.

Otherwise, you'll need to dig into Docker specifics about volume management. Sorry, I just really don't know much about it.
